2019-04-19T00:40:39.6812160-04:00 0HLM4G4LSU5E2:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:54470/api/Copyrights   (ca22a1cb)
2019-04-19T00:41:09.4507340-04:00 0HLM4G4LSU5E2:00000001 [INF] Executing action method "MM.DataServices.Controllers.CopyrightsController.Get (MM.DataServices)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2019-04-19T00:41:09.4843290-04:00 0HLM4G4LSU5E2:00000001 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2019-04-19T00:41:09.5696480-04:00 0HLM4G4LSU5E2:00000001 [INF] Executed action "MM.DataServices.Controllers.CopyrightsController.Get (MM.DataServices)" in 160.6401ms (afa2e885)
2019-04-19T00:41:09.5799450-04:00 0HLM4G4LSU5E2:00000001 [INF] Request finished in 29921.4664ms 200 text/plain; charset=utf-8 (791a596a)
2019-04-19T00:41:09.7279450-04:00 0HLM4G4LSU5E2:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:54470/favicon.ico   (ca22a1cb)
2019-04-19T00:41:10.1924510-04:00 0HLM4G4LSU5E2:00000002 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.IO.FileNotFoundException: Could not find file '/MM/Projects/MM.DataServices/MM.DataServices/wwwroot/lg/index.html'.
File name: '/MM/Projects/MM.DataServices/MM.DataServices/wwwroot/lg/index.html'
   at System.IO.FileInfo.get_Length()
   at Microsoft.AspNetCore.Http.SendFileResponseExtensions.SendFileAsyncCore(Stream outputStream, String fileName, Int64 offset, Nullable`1 count, CancellationToken cancel)
   at MM.DataServices.Startup.<>c__DisplayClass5_0.<<Configure>b__1>d.MoveNext() in /MM/Projects/MM.DataServices/MM.DataServices/Startup.cs:line 145
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2019-04-19T00:41:10.3219620-04:00 0HLM4G4LSU5E2:00000002 [INF] Request finished in 593.9491ms 500 text/html; charset=utf-8 (791a596a)
2019-04-19T00:50:15.9937220-04:00 0HLM4GA1LND4O:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:54470/api/Copyrights   (ca22a1cb)
2019-04-19T00:50:22.1579530-04:00 0HLM4GA1LND4O:00000001 [INF] Executing action method "MM.DataServices.Controllers.CopyrightsController.Get (MM.DataServices)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2019-04-19T00:50:22.1884470-04:00 0HLM4GA1LND4O:00000001 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2019-04-19T00:50:22.2611800-04:00 0HLM4GA1LND4O:00000001 [INF] Executed action "MM.DataServices.Controllers.CopyrightsController.Get (MM.DataServices)" in 142.6936ms (afa2e885)
2019-04-19T00:50:22.2712150-04:00 0HLM4GA1LND4O:00000001 [INF] Request finished in 6294.6361ms 200 text/plain; charset=utf-8 (791a596a)
2019-04-19T00:50:22.3777450-04:00 0HLM4GA1LND4O:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:54470/favicon.ico   (ca22a1cb)
2019-04-19T00:50:22.7629040-04:00 0HLM4GA1LND4O:00000002 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.IO.FileNotFoundException: Could not find file '/MM/Projects/MM.DataServices/MM.DataServices/wwwroot/lg/index.html'.
File name: '/MM/Projects/MM.DataServices/MM.DataServices/wwwroot/lg/index.html'
   at System.IO.FileInfo.get_Length()
   at Microsoft.AspNetCore.Http.SendFileResponseExtensions.SendFileAsyncCore(Stream outputStream, String fileName, Int64 offset, Nullable`1 count, CancellationToken cancel)
   at MM.DataServices.Startup.<>c__DisplayClass5_0.<<Configure>b__1>d.MoveNext() in /MM/Projects/MM.DataServices/MM.DataServices/Startup.cs:line 145
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2019-04-19T00:50:22.8669000-04:00 0HLM4GA1LND4O:00000002 [INF] Request finished in 489.1183ms 500 text/html; charset=utf-8 (791a596a)
2019-04-19T00:50:52.6630080-04:00 0HLM4GA1LND4R:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:54470/api/account/refreshtoken  0 (ca22a1cb)
2019-04-19T00:50:52.8574900-04:00 0HLM4GA1LND4R:00000001 [INF] Failed to validate the token "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwidW5pcXVlX25hbWUiOiJtYXJjX21hbnVlbEBob3RtYWlsLmNvbSIsImp0aSI6IjQ3NmRlNTJiLTI5NmUtNDZiMS1iMjdlLTA5YjcyY2Y4YzI1NCIsImlhdCI6IjA0LzE5LzIwMTkgMDE6MjQ6NTUiLCJuYmYiOjE1NTU2MzcwOTUsImV4cCI6MTU1NTcyMzQ5NSwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1NDQ3MC8ifQ.bIKJZBUpgWg-kOKMbfQUYJU5mjh1b-ndOwY0jJ4GIas". (f3081a27)
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidAudienceException: IDX10214: Audience validation failed. Audiences: 'http://localhost:54470/'. Did not match: validationParameters.ValidAudience: 'http://localhost:54470' or validationParameters.ValidAudiences: 'null'.
   at Microsoft.IdentityModel.Tokens.Validators.ValidateAudience(IEnumerable`1 audiences, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateTokenPayload(JwtSecurityToken jwt, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
2019-04-19T00:50:52.8592810-04:00 0HLM4GA1LND4R:00000001 [INF] "Bearer" was not authenticated. Failure message: "IDX10214: Audience validation failed. Audiences: 'http://localhost:54470/'. Did not match: validationParameters.ValidAudience: 'http://localhost:54470' or validationParameters.ValidAudiences: 'null'." (48071232)
2019-04-19T00:50:52.8871030-04:00 0HLM4GA1LND4R:00000001 [INF] Authorization failed for user: null. (a4ab1676)
2019-04-19T00:50:52.8900680-04:00 0HLM4GA1LND4R:00000001 [INF] Authorization failed for the request at filter '"Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter"'. (8b6446cb)
2019-04-19T00:50:52.8948120-04:00 0HLM4GA1LND4R:00000001 [INF] Executing ChallengeResult with authentication schemes ([]). (f3dca807)
2019-04-19T00:50:52.9113510-04:00 0HLM4GA1LND4R:00000001 [INF] AuthenticationScheme: "Bearer" was challenged. (d45f1f38)
2019-04-19T00:50:52.9114150-04:00 0HLM4GA1LND4R:00000001 [INF] Executed action "MM.DataServices.Controllers.AccountController.RefreshToken (MM.DataServices)" in 49.1084ms (afa2e885)
2019-04-19T00:50:52.9133320-04:00 0HLM4GA1LND4R:00000001 [INF] Request finished in 250.3632ms 401  (791a596a)
2019-04-19T00:51:33.3860830-04:00 0HLM4GA1LND4R:00000002 [INF] Request starting HTTP/1.1 POST http://localhost:54470/api/account/refreshtoken  0 (ca22a1cb)
2019-04-19T00:51:33.3865080-04:00 0HLM4GA1LND4R:00000002 [INF] Failed to validate the token "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwidW5pcXVlX25hbWUiOiJtYXJjX21hbnVlbEBob3RtYWlsLmNvbSIsImp0aSI6IjQ3NmRlNTJiLTI5NmUtNDZiMS1iMjdlLTA5YjcyY2Y4YzI1NCIsImlhdCI6IjA0LzE5LzIwMTkgMDE6MjQ6NTUiLCJuYmYiOjE1NTU2MzcwOTUsImV4cCI6MTU1NTcyMzQ5NSwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1NDQ3MC8ifQ.bIKJZBUpgWg-kOKMbfQUYJU5mjh1b-ndOwY0jJ4GIas". (f3081a27)
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidAudienceException: IDX10214: Audience validation failed. Audiences: 'http://localhost:54470/'. Did not match: validationParameters.ValidAudience: 'http://localhost:54470' or validationParameters.ValidAudiences: 'null'.
   at Microsoft.IdentityModel.Tokens.Validators.ValidateAudience(IEnumerable`1 audiences, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateTokenPayload(JwtSecurityToken jwt, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
2019-04-19T00:51:33.3865750-04:00 0HLM4GA1LND4R:00000002 [INF] "Bearer" was not authenticated. Failure message: "IDX10214: Audience validation failed. Audiences: 'http://localhost:54470/'. Did not match: validationParameters.ValidAudience: 'http://localhost:54470' or validationParameters.ValidAudiences: 'null'." (48071232)
2019-04-19T00:51:33.3894010-04:00 0HLM4GA1LND4R:00000002 [INF] Authorization failed for user: null. (a4ab1676)
2019-04-19T00:51:33.3894510-04:00 0HLM4GA1LND4R:00000002 [INF] Authorization failed for the request at filter '"Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter"'. (8b6446cb)
2019-04-19T00:51:33.3895370-04:00 0HLM4GA1LND4R:00000002 [INF] Executing ChallengeResult with authentication schemes ([]). (f3dca807)
2019-04-19T00:51:33.3896190-04:00 0HLM4GA1LND4R:00000002 [INF] AuthenticationScheme: "Bearer" was challenged. (d45f1f38)
2019-04-19T00:51:33.3896490-04:00 0HLM4GA1LND4R:00000002 [INF] Executed action "MM.DataServices.Controllers.AccountController.RefreshToken (MM.DataServices)" in 0.5299ms (afa2e885)
2019-04-19T00:51:33.3897270-04:00 0HLM4GA1LND4R:00000002 [INF] Request finished in 3.7283ms 401  (791a596a)
2019-04-19T00:53:07.5798770-04:00 0HLM4GA1LND4R:00000003 [INF] Request starting HTTP/1.1 POST http://localhost:54470/api/account/refreshtoken  0 (ca22a1cb)
2019-04-19T00:53:07.5804490-04:00 0HLM4GA1LND4R:00000003 [INF] Failed to validate the token "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwidW5pcXVlX25hbWUiOiJtYXJjX21hbnVlbEBob3RtYWlsLmNvbSIsImp0aSI6IjQ3NmRlNTJiLTI5NmUtNDZiMS1iMjdlLTA5YjcyY2Y4YzI1NCIsImlhdCI6IjA0LzE5LzIwMTkgMDE6MjQ6NTUiLCJuYmYiOjE1NTU2MzcwOTUsImV4cCI6MTU1NTcyMzQ5NSwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1NDQ3MC8ifQ.bIKJZBUpgWg-kOKMbfQUYJU5mjh1b-ndOwY0jJ4GIas". (f3081a27)
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidAudienceException: IDX10214: Audience validation failed. Audiences: 'http://localhost:54470/'. Did not match: validationParameters.ValidAudience: 'http://localhost:54470' or validationParameters.ValidAudiences: 'null'.
   at Microsoft.IdentityModel.Tokens.Validators.ValidateAudience(IEnumerable`1 audiences, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateTokenPayload(JwtSecurityToken jwt, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
2019-04-19T00:53:07.5804970-04:00 0HLM4GA1LND4R:00000003 [INF] "Bearer" was not authenticated. Failure message: "IDX10214: Audience validation failed. Audiences: 'http://localhost:54470/'. Did not match: validationParameters.ValidAudience: 'http://localhost:54470' or validationParameters.ValidAudiences: 'null'." (48071232)
2019-04-19T00:53:07.5806090-04:00 0HLM4GA1LND4R:00000003 [INF] Authorization failed for user: null. (a4ab1676)
2019-04-19T00:53:07.5806360-04:00 0HLM4GA1LND4R:00000003 [INF] Authorization failed for the request at filter '"Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter"'. (8b6446cb)
2019-04-19T00:53:07.5806990-04:00 0HLM4GA1LND4R:00000003 [INF] Executing ChallengeResult with authentication schemes ([]). (f3dca807)
2019-04-19T00:53:07.5807360-04:00 0HLM4GA1LND4R:00000003 [INF] AuthenticationScheme: "Bearer" was challenged. (d45f1f38)
2019-04-19T00:53:07.5807660-04:00 0HLM4GA1LND4R:00000003 [INF] Executed action "MM.DataServices.Controllers.AccountController.RefreshToken (MM.DataServices)" in 0.1866ms (afa2e885)
2019-04-19T00:53:07.5808530-04:00 0HLM4GA1LND4R:00000003 [INF] Request finished in 0.9995ms 401  (791a596a)
2019-04-19T00:54:46.7770080-04:00 0HLM4GCIC4KEA:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:54470/api/Copyrights   (ca22a1cb)
2019-04-19T00:54:53.6758450-04:00 0HLM4GCIC4KEA:00000001 [INF] Executing action method "MM.DataServices.Controllers.CopyrightsController.Get (MM.DataServices)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2019-04-19T00:54:53.7070980-04:00 0HLM4GCIC4KEA:00000001 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2019-04-19T00:54:53.7805250-04:00 0HLM4GCIC4KEA:00000001 [INF] Executed action "MM.DataServices.Controllers.CopyrightsController.Get (MM.DataServices)" in 143.1868ms (afa2e885)
2019-04-19T00:54:53.7921040-04:00 0HLM4GCIC4KEA:00000001 [INF] Request finished in 7031.8766ms 200 text/plain; charset=utf-8 (791a596a)
2019-04-19T00:54:53.8958640-04:00 0HLM4GCIC4KEA:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:54470/favicon.ico   (ca22a1cb)
2019-04-19T00:54:54.2683120-04:00 0HLM4GCIC4KEA:00000002 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.IO.FileNotFoundException: Could not find file '/MM/Projects/MM.DataServices/MM.DataServices/wwwroot/lg/index.html'.
File name: '/MM/Projects/MM.DataServices/MM.DataServices/wwwroot/lg/index.html'
   at System.IO.FileInfo.get_Length()
   at Microsoft.AspNetCore.Http.SendFileResponseExtensions.SendFileAsyncCore(Stream outputStream, String fileName, Int64 offset, Nullable`1 count, CancellationToken cancel)
   at MM.DataServices.Startup.<>c__DisplayClass5_0.<<Configure>b__1>d.MoveNext() in /MM/Projects/MM.DataServices/MM.DataServices/Startup.cs:line 145
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2019-04-19T00:54:54.3733580-04:00 0HLM4GCIC4KEA:00000002 [INF] Request finished in 477.4892ms 500 text/html; charset=utf-8 (791a596a)
2019-04-19T00:55:05.0317070-04:00 0HLM4GCIC4KED:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:54470/api/account/refreshtoken  0 (ca22a1cb)
2019-04-19T00:55:05.2127750-04:00 0HLM4GCIC4KED:00000001 [INF] Failed to validate the token "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwidW5pcXVlX25hbWUiOiJtYXJjX21hbnVlbEBob3RtYWlsLmNvbSIsImp0aSI6IjQ3NmRlNTJiLTI5NmUtNDZiMS1iMjdlLTA5YjcyY2Y4YzI1NCIsImlhdCI6IjA0LzE5LzIwMTkgMDE6MjQ6NTUiLCJuYmYiOjE1NTU2MzcwOTUsImV4cCI6MTU1NTcyMzQ5NSwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1NDQ3MC8ifQ.bIKJZBUpgWg-kOKMbfQUYJU5mjh1b-ndOwY0jJ4GIas". (f3081a27)
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidAudienceException: IDX10214: Audience validation failed. Audiences: 'http://localhost:54470/'. Did not match: validationParameters.ValidAudience: 'http://localhost:54470' or validationParameters.ValidAudiences: 'null'.
   at Microsoft.IdentityModel.Tokens.Validators.ValidateAudience(IEnumerable`1 audiences, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateTokenPayload(JwtSecurityToken jwt, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
2019-04-19T00:55:05.2162750-04:00 0HLM4GCIC4KED:00000001 [INF] "Bearer" was not authenticated. Failure message: "IDX10214: Audience validation failed. Audiences: 'http://localhost:54470/'. Did not match: validationParameters.ValidAudience: 'http://localhost:54470' or validationParameters.ValidAudiences: 'null'." (48071232)
2019-04-19T00:55:05.2422660-04:00 0HLM4GCIC4KED:00000001 [INF] Authorization failed for user: null. (a4ab1676)
2019-04-19T00:55:05.2456930-04:00 0HLM4GCIC4KED:00000001 [INF] Authorization failed for the request at filter '"Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter"'. (8b6446cb)
2019-04-19T00:55:05.2504940-04:00 0HLM4GCIC4KED:00000001 [INF] Executing ChallengeResult with authentication schemes ([]). (f3dca807)
2019-04-19T00:55:05.2663220-04:00 0HLM4GCIC4KED:00000001 [INF] AuthenticationScheme: "Bearer" was challenged. (d45f1f38)
2019-04-19T00:55:05.2663760-04:00 0HLM4GCIC4KED:00000001 [INF] Executed action "MM.DataServices.Controllers.AccountController.RefreshToken (MM.DataServices)" in 47.0874ms (afa2e885)
2019-04-19T00:55:05.2683090-04:00 0HLM4GCIC4KED:00000001 [INF] Request finished in 236.658ms 401  (791a596a)
2019-04-19T00:55:07.5644620-04:00 0HLM4GCIC4KED:00000002 [INF] Request starting HTTP/1.1 POST http://localhost:54470/api/account/refreshtoken  0 (ca22a1cb)
2019-04-19T00:55:07.5648990-04:00 0HLM4GCIC4KED:00000002 [INF] Failed to validate the token "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwidW5pcXVlX25hbWUiOiJtYXJjX21hbnVlbEBob3RtYWlsLmNvbSIsImp0aSI6IjQ3NmRlNTJiLTI5NmUtNDZiMS1iMjdlLTA5YjcyY2Y4YzI1NCIsImlhdCI6IjA0LzE5LzIwMTkgMDE6MjQ6NTUiLCJuYmYiOjE1NTU2MzcwOTUsImV4cCI6MTU1NTcyMzQ5NSwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1NDQ3MC8ifQ.bIKJZBUpgWg-kOKMbfQUYJU5mjh1b-ndOwY0jJ4GIas". (f3081a27)
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidAudienceException: IDX10214: Audience validation failed. Audiences: 'http://localhost:54470/'. Did not match: validationParameters.ValidAudience: 'http://localhost:54470' or validationParameters.ValidAudiences: 'null'.
   at Microsoft.IdentityModel.Tokens.Validators.ValidateAudience(IEnumerable`1 audiences, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateTokenPayload(JwtSecurityToken jwt, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
2019-04-19T00:55:07.5649560-04:00 0HLM4GCIC4KED:00000002 [INF] "Bearer" was not authenticated. Failure message: "IDX10214: Audience validation failed. Audiences: 'http://localhost:54470/'. Did not match: validationParameters.ValidAudience: 'http://localhost:54470' or validationParameters.ValidAudiences: 'null'." (48071232)
2019-04-19T00:55:07.5676260-04:00 0HLM4GCIC4KED:00000002 [INF] Authorization failed for user: null. (a4ab1676)
2019-04-19T00:55:07.5676840-04:00 0HLM4GCIC4KED:00000002 [INF] Authorization failed for the request at filter '"Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter"'. (8b6446cb)
2019-04-19T00:55:07.5677450-04:00 0HLM4GCIC4KED:00000002 [INF] Executing ChallengeResult with authentication schemes ([]). (f3dca807)
2019-04-19T00:55:07.5678710-04:00 0HLM4GCIC4KED:00000002 [INF] AuthenticationScheme: "Bearer" was challenged. (d45f1f38)
2019-04-19T00:55:07.5678960-04:00 0HLM4GCIC4KED:00000002 [INF] Executed action "MM.DataServices.Controllers.AccountController.RefreshToken (MM.DataServices)" in 0.579ms (afa2e885)
2019-04-19T00:55:07.5679780-04:00 0HLM4GCIC4KED:00000002 [INF] Request finished in 3.5721ms 401  (791a596a)
2019-04-19T00:55:38.9992960-04:00 0HLM4GCIC4KED:00000003 [INF] Request starting HTTP/1.1 PUT http://localhost:54470/api/account/token application/json 64 (ca22a1cb)
2019-04-19T00:55:39.2845260-04:00 0HLM4GCIC4KED:00000003 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.IO.FileNotFoundException: Could not find file '/MM/Projects/MM.DataServices/MM.DataServices/wwwroot/lg/index.html'.
File name: '/MM/Projects/MM.DataServices/MM.DataServices/wwwroot/lg/index.html'
   at System.IO.FileInfo.get_Length()
   at Microsoft.AspNetCore.Http.SendFileResponseExtensions.SendFileAsyncCore(Stream outputStream, String fileName, Int64 offset, Nullable`1 count, CancellationToken cancel)
   at MM.DataServices.Startup.<>c__DisplayClass5_0.<<Configure>b__1>d.MoveNext() in /MM/Projects/MM.DataServices/MM.DataServices/Startup.cs:line 145
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2019-04-19T00:55:39.3161540-04:00 0HLM4GCIC4KED:00000003 [INF] Request finished in 316.8696ms 500 text/html; charset=utf-8 (791a596a)
2019-04-19T00:55:47.9852550-04:00 0HLM4GCIC4KED:00000004 [INF] Request starting HTTP/1.1 POST http://localhost:54470/api/account/token application/json 64 (ca22a1cb)
2019-04-19T00:55:48.2029070-04:00 0HLM4GCIC4KED:00000004 [INF] Executing action method "MM.DataServices.Controllers.AccountController.CreateToken (MM.DataServices)" with arguments (["MM.DataServices.Controllers.AccountController+LoginModel"]) - ModelState is Valid (ba7f4ac2)
2019-04-19T00:55:56.2249630-04:00 0HLM4GCIC4KED:00000004 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2019-04-19T00:55:56.2251160-04:00 0HLM4GCIC4KED:00000004 [INF] Executed action "MM.DataServices.Controllers.AccountController.CreateToken (MM.DataServices)" in 8181.6135ms (afa2e885)
2019-04-19T00:55:56.2280890-04:00 0HLM4GCIC4KED:00000004 [INF] Request finished in 8242.6029ms 200 text/plain; charset=utf-8 (791a596a)
2019-04-19T00:57:42.6174650-04:00 0HLM4GCIC4KED:00000005 [INF] Request starting HTTP/1.1 POST http://localhost:54470/api/account/refreshtoken?Authorization=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwidW5pcXVlX25hbWUiOiJtYXJjX21hbnVlbEBob3RtYWlsLmNvbSIsImp0aSI6ImYyY2EyNDZmLTcyNjQtNGRiMi05NzcxLWY5NjA4MTIwMmVkMiIsImlhdCI6IjA0LzE5LzIwMTkgMDQ6NTU6NTYiLCJuYmYiOjE1NTU2NDk3NTYsImV4cCI6MTU1NTczNjE1NiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1NDQ3MCJ9.rlcWsZrj3qQ0eEpnGR9sVHZT24aAtiRVnkDq530L_zM  0 (ca22a1cb)
2019-04-19T00:57:42.6178590-04:00 0HLM4GCIC4KED:00000005 [INF] Failed to validate the token "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwidW5pcXVlX25hbWUiOiJtYXJjX21hbnVlbEBob3RtYWlsLmNvbSIsImp0aSI6IjQ3NmRlNTJiLTI5NmUtNDZiMS1iMjdlLTA5YjcyY2Y4YzI1NCIsImlhdCI6IjA0LzE5LzIwMTkgMDE6MjQ6NTUiLCJuYmYiOjE1NTU2MzcwOTUsImV4cCI6MTU1NTcyMzQ5NSwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1NDQ3MC8ifQ.bIKJZBUpgWg-kOKMbfQUYJU5mjh1b-ndOwY0jJ4GIas". (f3081a27)
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidAudienceException: IDX10214: Audience validation failed. Audiences: 'http://localhost:54470/'. Did not match: validationParameters.ValidAudience: 'http://localhost:54470' or validationParameters.ValidAudiences: 'null'.
   at Microsoft.IdentityModel.Tokens.Validators.ValidateAudience(IEnumerable`1 audiences, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateTokenPayload(JwtSecurityToken jwt, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
2019-04-19T00:57:42.6179020-04:00 0HLM4GCIC4KED:00000005 [INF] "Bearer" was not authenticated. Failure message: "IDX10214: Audience validation failed. Audiences: 'http://localhost:54470/'. Did not match: validationParameters.ValidAudience: 'http://localhost:54470' or validationParameters.ValidAudiences: 'null'." (48071232)
2019-04-19T00:57:42.6180060-04:00 0HLM4GCIC4KED:00000005 [INF] Authorization failed for user: null. (a4ab1676)
2019-04-19T00:57:42.6180420-04:00 0HLM4GCIC4KED:00000005 [INF] Authorization failed for the request at filter '"Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter"'. (8b6446cb)
2019-04-19T00:57:42.6180750-04:00 0HLM4GCIC4KED:00000005 [INF] Executing ChallengeResult with authentication schemes ([]). (f3dca807)
2019-04-19T00:57:42.6181060-04:00 0HLM4GCIC4KED:00000005 [INF] AuthenticationScheme: "Bearer" was challenged. (d45f1f38)
2019-04-19T00:57:42.6181260-04:00 0HLM4GCIC4KED:00000005 [INF] Executed action "MM.DataServices.Controllers.AccountController.RefreshToken (MM.DataServices)" in 0.1503ms (afa2e885)
2019-04-19T00:57:42.6181880-04:00 0HLM4GCIC4KED:00000005 [INF] Request finished in 0.7751ms 401  (791a596a)
2019-04-19T00:58:00.4841550-04:00 0HLM4GCIC4KED:00000006 [INF] Request starting HTTP/1.1 POST http://localhost:54470/api/account/refreshtoken?Authorization=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwidW5pcXVlX25hbWUiOiJtYXJjX21hbnVlbEBob3RtYWlsLmNvbSIsImp0aSI6ImYyY2EyNDZmLTcyNjQtNGRiMi05NzcxLWY5NjA4MTIwMmVkMiIsImlhdCI6IjA0LzE5LzIwMTkgMDQ6NTU6NTYiLCJuYmYiOjE1NTU2NDk3NTYsImV4cCI6MTU1NTczNjE1NiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1NDQ3MCJ9.rlcWsZrj3qQ0eEpnGR9sVHZT24aAtiRVnkDq530L_zM  0 (ca22a1cb)
2019-04-19T00:58:00.4846170-04:00 0HLM4GCIC4KED:00000006 [INF] Failed to validate the token "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwidW5pcXVlX25hbWUiOiJtYXJjX21hbnVlbEBob3RtYWlsLmNvbSIsImp0aSI6IjQ3NmRlNTJiLTI5NmUtNDZiMS1iMjdlLTA5YjcyY2Y4YzI1NCIsImlhdCI6IjA0LzE5LzIwMTkgMDE6MjQ6NTUiLCJuYmYiOjE1NTU2MzcwOTUsImV4cCI6MTU1NTcyMzQ5NSwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1NDQ3MC8ifQ.bIKJZBUpgWg-kOKMbfQUYJU5mjh1b-ndOwY0jJ4GIas". (f3081a27)
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidAudienceException: IDX10214: Audience validation failed. Audiences: 'http://localhost:54470/'. Did not match: validationParameters.ValidAudience: 'http://localhost:54470' or validationParameters.ValidAudiences: 'null'.
   at Microsoft.IdentityModel.Tokens.Validators.ValidateAudience(IEnumerable`1 audiences, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateTokenPayload(JwtSecurityToken jwt, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
2019-04-19T00:58:00.4846690-04:00 0HLM4GCIC4KED:00000006 [INF] "Bearer" was not authenticated. Failure message: "IDX10214: Audience validation failed. Audiences: 'http://localhost:54470/'. Did not match: validationParameters.ValidAudience: 'http://localhost:54470' or validationParameters.ValidAudiences: 'null'." (48071232)
2019-04-19T00:58:00.4848930-04:00 0HLM4GCIC4KED:00000006 [INF] Authorization failed for user: null. (a4ab1676)
2019-04-19T00:58:00.4849350-04:00 0HLM4GCIC4KED:00000006 [INF] Authorization failed for the request at filter '"Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter"'. (8b6446cb)
2019-04-19T00:58:00.4849660-04:00 0HLM4GCIC4KED:00000006 [INF] Executing ChallengeResult with authentication schemes ([]). (f3dca807)
2019-04-19T00:58:00.4849980-04:00 0HLM4GCIC4KED:00000006 [INF] AuthenticationScheme: "Bearer" was challenged. (d45f1f38)
2019-04-19T00:58:00.4850310-04:00 0HLM4GCIC4KED:00000006 [INF] Executed action "MM.DataServices.Controllers.AccountController.RefreshToken (MM.DataServices)" in 0.1748ms (afa2e885)
2019-04-19T00:58:00.4850990-04:00 0HLM4GCIC4KED:00000006 [INF] Request finished in 0.9756ms 401  (791a596a)
2019-04-19T01:01:32.1510850-04:00 0HLM4GCIC4KED:00000007 [INF] Request starting HTTP/1.1 POST http://localhost:54470/api/account/refreshtoken?Authorization=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwidW5pcXVlX25hbWUiOiJtYXJjX21hbnVlbEBob3RtYWlsLmNvbSIsImp0aSI6ImYyY2EyNDZmLTcyNjQtNGRiMi05NzcxLWY5NjA4MTIwMmVkMiIsImlhdCI6IjA0LzE5LzIwMTkgMDQ6NTU6NTYiLCJuYmYiOjE1NTU2NDk3NTYsImV4cCI6MTU1NTczNjE1NiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1NDQ3MCJ9.rlcWsZrj3qQ0eEpnGR9sVHZT24aAtiRVnkDq530L_zM  0 (ca22a1cb)
2019-04-19T01:01:32.1520310-04:00 0HLM4GCIC4KED:00000007 [INF] Failed to validate the token "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwidW5pcXVlX25hbWUiOiJtYXJjX21hbnVlbEBob3RtYWlsLmNvbSIsImp0aSI6IjQ3NmRlNTJiLTI5NmUtNDZiMS1iMjdlLTA5YjcyY2Y4YzI1NCIsImlhdCI6IjA0LzE5LzIwMTkgMDE6MjQ6NTUiLCJuYmYiOjE1NTU2MzcwOTUsImV4cCI6MTU1NTcyMzQ5NSwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1NDQ3MC8ifQ.bIKJZBUpgWg-kOKMbfQUYJU5mjh1b-ndOwY0jJ4GIas". (f3081a27)
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidAudienceException: IDX10214: Audience validation failed. Audiences: 'http://localhost:54470/'. Did not match: validationParameters.ValidAudience: 'http://localhost:54470' or validationParameters.ValidAudiences: 'null'.
   at Microsoft.IdentityModel.Tokens.Validators.ValidateAudience(IEnumerable`1 audiences, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateTokenPayload(JwtSecurityToken jwt, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
2019-04-19T01:01:32.1521290-04:00 0HLM4GCIC4KED:00000007 [INF] "Bearer" was not authenticated. Failure message: "IDX10214: Audience validation failed. Audiences: 'http://localhost:54470/'. Did not match: validationParameters.ValidAudience: 'http://localhost:54470' or validationParameters.ValidAudiences: 'null'." (48071232)
2019-04-19T01:01:32.1522680-04:00 0HLM4GCIC4KED:00000007 [INF] Authorization failed for user: null. (a4ab1676)
2019-04-19T01:01:32.1523070-04:00 0HLM4GCIC4KED:00000007 [INF] Authorization failed for the request at filter '"Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter"'. (8b6446cb)
2019-04-19T01:01:32.1524060-04:00 0HLM4GCIC4KED:00000007 [INF] Executing ChallengeResult with authentication schemes ([]). (f3dca807)
2019-04-19T01:01:32.1524530-04:00 0HLM4GCIC4KED:00000007 [INF] AuthenticationScheme: "Bearer" was challenged. (d45f1f38)
2019-04-19T01:01:32.1524790-04:00 0HLM4GCIC4KED:00000007 [INF] Executed action "MM.DataServices.Controllers.AccountController.RefreshToken (MM.DataServices)" in 0.2465ms (afa2e885)
2019-04-19T01:01:32.1525770-04:00 0HLM4GCIC4KED:00000007 [INF] Request finished in 1.7189ms 401  (791a596a)
2019-04-19T01:03:54.4701160-04:00 0HLM4GHLIMAR8:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:54470/api/Copyrights   (ca22a1cb)
2019-04-19T01:03:55.0815850-04:00 0HLM4GHLIMAR8:00000001 [INF] Executing action method "MM.DataServices.Controllers.CopyrightsController.Get (MM.DataServices)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2019-04-19T01:03:55.1126100-04:00 0HLM4GHLIMAR8:00000001 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2019-04-19T01:03:55.1865630-04:00 0HLM4GHLIMAR8:00000001 [INF] Executed action "MM.DataServices.Controllers.CopyrightsController.Get (MM.DataServices)" in 144.3342ms (afa2e885)
2019-04-19T01:03:55.1964810-04:00 0HLM4GHLIMAR8:00000001 [INF] Request finished in 746.4353ms 200 text/plain; charset=utf-8 (791a596a)
2019-04-19T01:03:55.3107720-04:00 0HLM4GHLIMAR8:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:54470/favicon.ico   (ca22a1cb)
2019-04-19T01:03:55.8032130-04:00 0HLM4GHLIMAR8:00000002 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.IO.FileNotFoundException: Could not find file '/MM/Projects/MM.DataServices/MM.DataServices/wwwroot/lg/index.html'.
File name: '/MM/Projects/MM.DataServices/MM.DataServices/wwwroot/lg/index.html'
   at System.IO.FileInfo.get_Length()
   at Microsoft.AspNetCore.Http.SendFileResponseExtensions.SendFileAsyncCore(Stream outputStream, String fileName, Int64 offset, Nullable`1 count, CancellationToken cancel)
   at MM.DataServices.Startup.<>c__DisplayClass5_0.<<Configure>b__1>d.MoveNext() in /MM/Projects/MM.DataServices/MM.DataServices/Startup.cs:line 145
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2019-04-19T01:03:55.9255130-04:00 0HLM4GHLIMAR8:00000002 [INF] Request finished in 614.7274ms 500 text/html; charset=utf-8 (791a596a)
2019-04-19T01:08:19.2610200-04:00 0HLM4GHLIMARB:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:54470/api/account/refreshtoken?Authorization=Bearer%20eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwidW5pcXVlX25hbWUiOiJtYXJjX21hbnVlbEBob3RtYWlsLmNvbSIsImp0aSI6ImYyY2EyNDZmLTcyNjQtNGRiMi05NzcxLWY5NjA4MTIwMmVkMiIsImlhdCI6IjA0LzE5LzIwMTkgMDQ6NTU6NTYiLCJuYmYiOjE1NTU2NDk3NTYsImV4cCI6MTU1NTczNjE1NiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1NDQ3MCJ9.rlcWsZrj3qQ0eEpnGR9sVHZT24aAtiRVnkDq530L_zM  0 (ca22a1cb)
2019-04-19T01:08:19.4287060-04:00 0HLM4GHLIMARB:00000001 [INF] Failed to validate the token "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwidW5pcXVlX25hbWUiOiJtYXJjX21hbnVlbEBob3RtYWlsLmNvbSIsImp0aSI6IjQ3NmRlNTJiLTI5NmUtNDZiMS1iMjdlLTA5YjcyY2Y4YzI1NCIsImlhdCI6IjA0LzE5LzIwMTkgMDE6MjQ6NTUiLCJuYmYiOjE1NTU2MzcwOTUsImV4cCI6MTU1NTcyMzQ5NSwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1NDQ3MC8ifQ.bIKJZBUpgWg-kOKMbfQUYJU5mjh1b-ndOwY0jJ4GIas". (f3081a27)
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidIssuerException: IDX10211: Unable to validate issuer. The 'issuer' parameter is null or whitespace
   at Microsoft.IdentityModel.Tokens.Validators.ValidateIssuer(String issuer, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateTokenPayload(JwtSecurityToken jwt, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
2019-04-19T01:08:19.4305080-04:00 0HLM4GHLIMARB:00000001 [INF] "Bearer" was not authenticated. Failure message: "IDX10211: Unable to validate issuer. The 'issuer' parameter is null or whitespace" (48071232)
2019-04-19T01:08:19.4556830-04:00 0HLM4GHLIMARB:00000001 [INF] Authorization failed for user: null. (a4ab1676)
2019-04-19T01:08:19.4586580-04:00 0HLM4GHLIMARB:00000001 [INF] Authorization failed for the request at filter '"Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter"'. (8b6446cb)
2019-04-19T01:08:19.4633500-04:00 0HLM4GHLIMARB:00000001 [INF] Executing ChallengeResult with authentication schemes ([]). (f3dca807)
2019-04-19T01:08:19.4791710-04:00 0HLM4GHLIMARB:00000001 [INF] AuthenticationScheme: "Bearer" was challenged. (d45f1f38)
2019-04-19T01:08:19.4792240-04:00 0HLM4GHLIMARB:00000001 [INF] Executed action "MM.DataServices.Controllers.AccountController.RefreshToken (MM.DataServices)" in 45.8547ms (afa2e885)
2019-04-19T01:08:19.4811260-04:00 0HLM4GHLIMARB:00000001 [INF] Request finished in 220.1736ms 401  (791a596a)
2019-04-19T01:09:36.9301880-04:00 0HLM4GKRKPEQ4:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:54470/api/Copyrights   (ca22a1cb)
2019-04-19T01:09:37.5706580-04:00 0HLM4GKRKPEQ4:00000001 [INF] Executing action method "MM.DataServices.Controllers.CopyrightsController.Get (MM.DataServices)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2019-04-19T01:09:37.6030300-04:00 0HLM4GKRKPEQ4:00000001 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2019-04-19T01:09:37.6774820-04:00 0HLM4GKRKPEQ4:00000001 [INF] Executed action "MM.DataServices.Controllers.CopyrightsController.Get (MM.DataServices)" in 147.0342ms (afa2e885)
2019-04-19T01:09:37.6870470-04:00 0HLM4GKRKPEQ4:00000001 [INF] Request finished in 773.9575ms 200 text/plain; charset=utf-8 (791a596a)
2019-04-19T01:09:37.7885980-04:00 0HLM4GKRKPEQ4:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:54470/favicon.ico   (ca22a1cb)
2019-04-19T01:09:38.2594050-04:00 0HLM4GKRKPEQ4:00000002 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.IO.FileNotFoundException: Could not find file '/MM/Projects/MM.DataServices/MM.DataServices/wwwroot/lg/index.html'.
File name: '/MM/Projects/MM.DataServices/MM.DataServices/wwwroot/lg/index.html'
   at System.IO.FileInfo.get_Length()
   at Microsoft.AspNetCore.Http.SendFileResponseExtensions.SendFileAsyncCore(Stream outputStream, String fileName, Int64 offset, Nullable`1 count, CancellationToken cancel)
   at MM.DataServices.Startup.<>c__DisplayClass5_0.<<Configure>b__1>d.MoveNext() in /MM/Projects/MM.DataServices/MM.DataServices/Startup.cs:line 145
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2019-04-19T01:09:38.3683120-04:00 0HLM4GKRKPEQ4:00000002 [INF] Request finished in 579.7092ms 500 text/html; charset=utf-8 (791a596a)
2019-04-19T01:10:15.7948130-04:00 0HLM4GKRKPEQ7:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:54470/api/account/refreshtoken?Authorization=Bearer%20eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwidW5pcXVlX25hbWUiOiJtYXJjX21hbnVlbEBob3RtYWlsLmNvbSIsImp0aSI6ImYyY2EyNDZmLTcyNjQtNGRiMi05NzcxLWY5NjA4MTIwMmVkMiIsImlhdCI6IjA0LzE5LzIwMTkgMDQ6NTU6NTYiLCJuYmYiOjE1NTU2NDk3NTYsImV4cCI6MTU1NTczNjE1NiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1NDQ3MCJ9.rlcWsZrj3qQ0eEpnGR9sVHZT24aAtiRVnkDq530L_zM  0 (ca22a1cb)
2019-04-19T01:10:15.9716190-04:00 0HLM4GKRKPEQ7:00000001 [INF] Failed to validate the token "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwidW5pcXVlX25hbWUiOiJtYXJjX21hbnVlbEBob3RtYWlsLmNvbSIsImp0aSI6IjQ3NmRlNTJiLTI5NmUtNDZiMS1iMjdlLTA5YjcyY2Y4YzI1NCIsImlhdCI6IjA0LzE5LzIwMTkgMDE6MjQ6NTUiLCJuYmYiOjE1NTU2MzcwOTUsImV4cCI6MTU1NTcyMzQ5NSwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1NDQ3MC8ifQ.bIKJZBUpgWg-kOKMbfQUYJU5mjh1b-ndOwY0jJ4GIas". (f3081a27)
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidAudienceException: IDX10214: Audience validation failed. Audiences: 'http://localhost:54470/'. Did not match: validationParameters.ValidAudience: 'http://localhost:54470' or validationParameters.ValidAudiences: 'null'.
   at Microsoft.IdentityModel.Tokens.Validators.ValidateAudience(IEnumerable`1 audiences, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateTokenPayload(JwtSecurityToken jwt, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
2019-04-19T01:10:15.9733900-04:00 0HLM4GKRKPEQ7:00000001 [INF] "Bearer" was not authenticated. Failure message: "IDX10214: Audience validation failed. Audiences: 'http://localhost:54470/'. Did not match: validationParameters.ValidAudience: 'http://localhost:54470' or validationParameters.ValidAudiences: 'null'." (48071232)
2019-04-19T01:10:15.9987050-04:00 0HLM4GKRKPEQ7:00000001 [INF] Authorization failed for user: null. (a4ab1676)
2019-04-19T01:10:16.0016860-04:00 0HLM4GKRKPEQ7:00000001 [INF] Authorization failed for the request at filter '"Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter"'. (8b6446cb)
2019-04-19T01:10:16.0064330-04:00 0HLM4GKRKPEQ7:00000001 [INF] Executing ChallengeResult with authentication schemes ([]). (f3dca807)
2019-04-19T01:10:16.0220920-04:00 0HLM4GKRKPEQ7:00000001 [INF] AuthenticationScheme: "Bearer" was challenged. (d45f1f38)
2019-04-19T01:10:16.0221470-04:00 0HLM4GKRKPEQ7:00000001 [INF] Executed action "MM.DataServices.Controllers.AccountController.RefreshToken (MM.DataServices)" in 45.9011ms (afa2e885)
2019-04-19T01:10:16.0240740-04:00 0HLM4GKRKPEQ7:00000001 [INF] Request finished in 229.3297ms 401  (791a596a)
2019-04-19T01:11:14.4884630-04:00 0HLM4GKRKPEQ7:00000002 [INF] Request starting HTTP/1.1 POST http://localhost:54470/api/account/refreshtoken?Authorization=Bearer%20eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwidW5pcXVlX25hbWUiOiJtYXJjX21hbnVlbEBob3RtYWlsLmNvbSIsImp0aSI6ImYyY2EyNDZmLTcyNjQtNGRiMi05NzcxLWY5NjA4MTIwMmVkMiIsImlhdCI6IjA0LzE5LzIwMTkgMDQ6NTU6NTYiLCJuYmYiOjE1NTU2NDk3NTYsImV4cCI6MTU1NTczNjE1NiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1NDQ3MCJ9.rlcWsZrj3qQ0eEpnGR9sVHZT24aAtiRVnkDq530L_zM  0 (ca22a1cb)
2019-04-19T01:11:14.4889220-04:00 0HLM4GKRKPEQ7:00000002 [INF] Failed to validate the token "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwidW5pcXVlX25hbWUiOiJtYXJjX21hbnVlbEBob3RtYWlsLmNvbSIsImp0aSI6IjQ3NmRlNTJiLTI5NmUtNDZiMS1iMjdlLTA5YjcyY2Y4YzI1NCIsImlhdCI6IjA0LzE5LzIwMTkgMDE6MjQ6NTUiLCJuYmYiOjE1NTU2MzcwOTUsImV4cCI6MTU1NTcyMzQ5NSwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1NDQ3MC8ifQ.bIKJZBUpgWg-kOKMbfQUYJU5mjh1b-ndOwY0jJ4GIas". (f3081a27)
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidAudienceException: IDX10214: Audience validation failed. Audiences: 'http://localhost:54470/'. Did not match: validationParameters.ValidAudience: 'http://localhost:54470' or validationParameters.ValidAudiences: 'null'.
   at Microsoft.IdentityModel.Tokens.Validators.ValidateAudience(IEnumerable`1 audiences, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateTokenPayload(JwtSecurityToken jwt, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
2019-04-19T01:11:14.4889760-04:00 0HLM4GKRKPEQ7:00000002 [INF] "Bearer" was not authenticated. Failure message: "IDX10214: Audience validation failed. Audiences: 'http://localhost:54470/'. Did not match: validationParameters.ValidAudience: 'http://localhost:54470' or validationParameters.ValidAudiences: 'null'." (48071232)
2019-04-19T01:11:14.4918590-04:00 0HLM4GKRKPEQ7:00000002 [INF] Authorization failed for user: null. (a4ab1676)
2019-04-19T01:11:14.4919110-04:00 0HLM4GKRKPEQ7:00000002 [INF] Authorization failed for the request at filter '"Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter"'. (8b6446cb)
2019-04-19T01:11:14.4919700-04:00 0HLM4GKRKPEQ7:00000002 [INF] Executing ChallengeResult with authentication schemes ([]). (f3dca807)
2019-04-19T01:11:14.4920670-04:00 0HLM4GKRKPEQ7:00000002 [INF] AuthenticationScheme: "Bearer" was challenged. (d45f1f38)
2019-04-19T01:11:14.4920950-04:00 0HLM4GKRKPEQ7:00000002 [INF] Executed action "MM.DataServices.Controllers.AccountController.RefreshToken (MM.DataServices)" in 0.6728ms (afa2e885)
2019-04-19T01:11:14.4921710-04:00 0HLM4GKRKPEQ7:00000002 [INF] Request finished in 3.7675ms 401  (791a596a)
2019-04-19T01:11:27.8964740-04:00 0HLM4GLSNJPR2:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:54470/api/Copyrights   (ca22a1cb)
2019-04-19T01:11:28.5147380-04:00 0HLM4GLSNJPR2:00000001 [INF] Executing action method "MM.DataServices.Controllers.CopyrightsController.Get (MM.DataServices)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2019-04-19T01:11:28.5464500-04:00 0HLM4GLSNJPR2:00000001 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2019-04-19T01:11:28.6201360-04:00 0HLM4GLSNJPR2:00000001 [INF] Executed action "MM.DataServices.Controllers.CopyrightsController.Get (MM.DataServices)" in 144.8786ms (afa2e885)
2019-04-19T01:11:28.6296280-04:00 0HLM4GLSNJPR2:00000001 [INF] Request finished in 753.0521ms 200 text/plain; charset=utf-8 (791a596a)
2019-04-19T01:11:28.7391120-04:00 0HLM4GLSNJPR2:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:54470/favicon.ico   (ca22a1cb)
2019-04-19T01:11:29.2522570-04:00 0HLM4GLSNJPR2:00000002 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.IO.FileNotFoundException: Could not find file '/MM/Projects/MM.DataServices/MM.DataServices/wwwroot/lg/index.html'.
File name: '/MM/Projects/MM.DataServices/MM.DataServices/wwwroot/lg/index.html'
   at System.IO.FileInfo.get_Length()
   at Microsoft.AspNetCore.Http.SendFileResponseExtensions.SendFileAsyncCore(Stream outputStream, String fileName, Int64 offset, Nullable`1 count, CancellationToken cancel)
   at MM.DataServices.Startup.<>c__DisplayClass5_0.<<Configure>b__1>d.MoveNext() in /MM/Projects/MM.DataServices/MM.DataServices/Startup.cs:line 145
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2019-04-19T01:11:29.3588170-04:00 0HLM4GLSNJPR2:00000002 [INF] Request finished in 619.6913ms 500 text/html; charset=utf-8 (791a596a)
2019-04-19T01:11:42.3641990-04:00 0HLM4GLSNJPR5:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:54470/api/account/refreshtoken?Authorization=Bearer%20eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwidW5pcXVlX25hbWUiOiJtYXJjX21hbnVlbEBob3RtYWlsLmNvbSIsImp0aSI6ImYyY2EyNDZmLTcyNjQtNGRiMi05NzcxLWY5NjA4MTIwMmVkMiIsImlhdCI6IjA0LzE5LzIwMTkgMDQ6NTU6NTYiLCJuYmYiOjE1NTU2NDk3NTYsImV4cCI6MTU1NTczNjE1NiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1NDQ3MCJ9.rlcWsZrj3qQ0eEpnGR9sVHZT24aAtiRVnkDq530L_zM  0 (ca22a1cb)
2019-04-19T01:11:42.5456190-04:00 0HLM4GLSNJPR5:00000001 [INF] Failed to validate the token "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwidW5pcXVlX25hbWUiOiJtYXJjX21hbnVlbEBob3RtYWlsLmNvbSIsImp0aSI6IjQ3NmRlNTJiLTI5NmUtNDZiMS1iMjdlLTA5YjcyY2Y4YzI1NCIsImlhdCI6IjA0LzE5LzIwMTkgMDE6MjQ6NTUiLCJuYmYiOjE1NTU2MzcwOTUsImV4cCI6MTU1NTcyMzQ5NSwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1NDQ3MC8ifQ.bIKJZBUpgWg-kOKMbfQUYJU5mjh1b-ndOwY0jJ4GIas". (f3081a27)
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidIssuerException: IDX10211: Unable to validate issuer. The 'issuer' parameter is null or whitespace
   at Microsoft.IdentityModel.Tokens.Validators.ValidateIssuer(String issuer, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateTokenPayload(JwtSecurityToken jwt, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
2019-04-19T01:11:42.5473840-04:00 0HLM4GLSNJPR5:00000001 [INF] "Bearer" was not authenticated. Failure message: "IDX10211: Unable to validate issuer. The 'issuer' parameter is null or whitespace" (48071232)
2019-04-19T01:11:42.5727700-04:00 0HLM4GLSNJPR5:00000001 [INF] Authorization failed for user: null. (a4ab1676)
2019-04-19T01:11:42.5757670-04:00 0HLM4GLSNJPR5:00000001 [INF] Authorization failed for the request at filter '"Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter"'. (8b6446cb)
2019-04-19T01:11:42.5804440-04:00 0HLM4GLSNJPR5:00000001 [INF] Executing ChallengeResult with authentication schemes ([]). (f3dca807)
2019-04-19T01:11:42.5960170-04:00 0HLM4GLSNJPR5:00000001 [INF] AuthenticationScheme: "Bearer" was challenged. (d45f1f38)
2019-04-19T01:11:42.5960740-04:00 0HLM4GLSNJPR5:00000001 [INF] Executed action "MM.DataServices.Controllers.AccountController.RefreshToken (MM.DataServices)" in 45.8203ms (afa2e885)
2019-04-19T01:11:42.5979950-04:00 0HLM4GLSNJPR5:00000001 [INF] Request finished in 233.8405ms 401  (791a596a)
2019-04-19T01:15:41.7373120-04:00 0HLM4GLSNJPR5:00000002 [INF] Request starting HTTP/1.1 POST http://localhost:54470/api/account/refreshtoken?Authorization=Bearer%20eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwidW5pcXVlX25hbWUiOiJtYXJjX21hbnVlbEBob3RtYWlsLmNvbSIsImp0aSI6ImYyY2EyNDZmLTcyNjQtNGRiMi05NzcxLWY5NjA4MTIwMmVkMiIsImlhdCI6IjA0LzE5LzIwMTkgMDQ6NTU6NTYiLCJuYmYiOjE1NTU2NDk3NTYsImV4cCI6MTU1NTczNjE1NiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1NDQ3MCJ9.rlcWsZrj3qQ0eEpnGR9sVHZT24aAtiRVnkDq530L_zM  0 (ca22a1cb)
2019-04-19T01:15:41.7377070-04:00 0HLM4GLSNJPR5:00000002 [INF] Failed to validate the token "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwidW5pcXVlX25hbWUiOiJtYXJjX21hbnVlbEBob3RtYWlsLmNvbSIsImp0aSI6IjQ3NmRlNTJiLTI5NmUtNDZiMS1iMjdlLTA5YjcyY2Y4YzI1NCIsImlhdCI6IjA0LzE5LzIwMTkgMDE6MjQ6NTUiLCJuYmYiOjE1NTU2MzcwOTUsImV4cCI6MTU1NTcyMzQ5NSwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1NDQ3MC8ifQ.bIKJZBUpgWg-kOKMbfQUYJU5mjh1b-ndOwY0jJ4GIas". (f3081a27)
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidIssuerException: IDX10211: Unable to validate issuer. The 'issuer' parameter is null or whitespace
   at Microsoft.IdentityModel.Tokens.Validators.ValidateIssuer(String issuer, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateTokenPayload(JwtSecurityToken jwt, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
2019-04-19T01:15:41.7377580-04:00 0HLM4GLSNJPR5:00000002 [INF] "Bearer" was not authenticated. Failure message: "IDX10211: Unable to validate issuer. The 'issuer' parameter is null or whitespace" (48071232)
2019-04-19T01:15:41.7406100-04:00 0HLM4GLSNJPR5:00000002 [INF] Authorization failed for user: null. (a4ab1676)
2019-04-19T01:15:41.7406570-04:00 0HLM4GLSNJPR5:00000002 [INF] Authorization failed for the request at filter '"Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter"'. (8b6446cb)
2019-04-19T01:15:41.7407190-04:00 0HLM4GLSNJPR5:00000002 [INF] Executing ChallengeResult with authentication schemes ([]). (f3dca807)
2019-04-19T01:15:41.7408000-04:00 0HLM4GLSNJPR5:00000002 [INF] AuthenticationScheme: "Bearer" was challenged. (d45f1f38)
2019-04-19T01:15:41.7408230-04:00 0HLM4GLSNJPR5:00000002 [INF] Executed action "MM.DataServices.Controllers.AccountController.RefreshToken (MM.DataServices)" in 0.5463ms (afa2e885)
2019-04-19T01:15:41.7409080-04:00 0HLM4GLSNJPR5:00000002 [INF] Request finished in 3.6484ms 401  (791a596a)
2019-04-19T01:19:45.5555790-04:00 0HLM4GQH12KMD:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:54470/api/Copyrights   (ca22a1cb)
2019-04-19T01:19:46.1722650-04:00 0HLM4GQH12KMD:00000001 [INF] Executing action method "MM.DataServices.Controllers.CopyrightsController.Get (MM.DataServices)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2019-04-19T01:19:46.2031660-04:00 0HLM4GQH12KMD:00000001 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2019-04-19T01:19:46.2792640-04:00 0HLM4GQH12KMD:00000001 [INF] Executed action "MM.DataServices.Controllers.CopyrightsController.Get (MM.DataServices)" in 147.1717ms (afa2e885)
2019-04-19T01:19:46.2893060-04:00 0HLM4GQH12KMD:00000001 [INF] Request finished in 750.2302ms 200 text/plain; charset=utf-8 (791a596a)
2019-04-19T01:19:46.3956300-04:00 0HLM4GQH12KMD:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:54470/favicon.ico   (ca22a1cb)
2019-04-19T01:19:46.8820240-04:00 0HLM4GQH12KMD:00000002 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.IO.FileNotFoundException: Could not find file '/MM/Projects/MM.DataServices/MM.DataServices/wwwroot/lg/index.html'.
File name: '/MM/Projects/MM.DataServices/MM.DataServices/wwwroot/lg/index.html'
   at System.IO.FileInfo.get_Length()
   at Microsoft.AspNetCore.Http.SendFileResponseExtensions.SendFileAsyncCore(Stream outputStream, String fileName, Int64 offset, Nullable`1 count, CancellationToken cancel)
   at MM.DataServices.Startup.<>c__DisplayClass5_0.<<Configure>b__1>d.MoveNext() in /MM/Projects/MM.DataServices/MM.DataServices/Startup.cs:line 145
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2019-04-19T01:19:46.9887620-04:00 0HLM4GQH12KMD:00000002 [INF] Request finished in 593.1015ms 500 text/html; charset=utf-8 (791a596a)
2019-04-19T01:19:56.8168360-04:00 0HLM4GQH12KMF:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:54470/api/account/refreshtoken?Authorization=Bearer%20eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwidW5pcXVlX25hbWUiOiJtYXJjX21hbnVlbEBob3RtYWlsLmNvbSIsImp0aSI6ImYyY2EyNDZmLTcyNjQtNGRiMi05NzcxLWY5NjA4MTIwMmVkMiIsImlhdCI6IjA0LzE5LzIwMTkgMDQ6NTU6NTYiLCJuYmYiOjE1NTU2NDk3NTYsImV4cCI6MTU1NTczNjE1NiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1NDQ3MCJ9.rlcWsZrj3qQ0eEpnGR9sVHZT24aAtiRVnkDq530L_zM  0 (ca22a1cb)
2019-04-19T01:19:57.0274900-04:00 0HLM4GQH12KMF:00000001 [INF] Successfully validated the token. (60169667)
2019-04-19T01:19:57.0570860-04:00 0HLM4GQH12KMF:00000001 [INF] Authorization was successful for user: "marc_manuel@hotmail.com". (d7eb274a)
2019-04-19T01:19:57.0577360-04:00 0HLM4GQH12KMF:00000001 [INF] Executing action method "MM.DataServices.Controllers.AccountController.RefreshToken (MM.DataServices)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2019-04-19T01:20:53.3768050-04:00 0HLM4GQH12KMF:00000001 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2019-04-19T01:20:53.3769970-04:00 0HLM4GQH12KMF:00000001 [INF] Executed action "MM.DataServices.Controllers.AccountController.RefreshToken (MM.DataServices)" in 56340.2187ms (afa2e885)
2019-04-19T01:20:53.3770570-04:00 0HLM4GQH12KMF:00000001 [INF] Request finished in 56558.5698ms 200 text/plain; charset=utf-8 (791a596a)
2019-04-19T09:30:53.7886290-04:00 0HLM4GQH12KMG:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:54470/api/Copyrights   (ca22a1cb)
2019-04-19T09:30:53.8002840-04:00 0HLM4GQH12KMG:00000001 [INF] Executing action method "MM.DataServices.Controllers.CopyrightsController.Get (MM.DataServices)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2019-04-19T09:30:53.8009040-04:00 0HLM4GQH12KMG:00000001 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2019-04-19T09:30:53.8012820-04:00 0HLM4GQH12KMG:00000001 [INF] Executed action "MM.DataServices.Controllers.CopyrightsController.Get (MM.DataServices)" in 1.7571ms (afa2e885)
2019-04-19T09:30:53.8014700-04:00 0HLM4GQH12KMG:00000001 [INF] Request finished in 16.2063ms 200 text/plain; charset=utf-8 (791a596a)
2019-04-19T09:30:53.8142970-04:00 0HLM4GQH12KMG:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:54470/favicon.ico   (ca22a1cb)
2019-04-19T09:30:54.1187020-04:00 0HLM4GQH12KMG:00000002 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.IO.FileNotFoundException: Could not find file '/MM/Projects/MM.DataServices/MM.DataServices/wwwroot/lg/index.html'.
File name: '/MM/Projects/MM.DataServices/MM.DataServices/wwwroot/lg/index.html'
   at System.IO.FileInfo.get_Length()
   at Microsoft.AspNetCore.Http.SendFileResponseExtensions.SendFileAsyncCore(Stream outputStream, String fileName, Int64 offset, Nullable`1 count, CancellationToken cancel)
   at MM.DataServices.Startup.<>c__DisplayClass5_0.<<Configure>b__1>d.MoveNext() in /MM/Projects/MM.DataServices/MM.DataServices/Startup.cs:line 145
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2019-04-19T09:30:54.1358450-04:00 0HLM4GQH12KMG:00000002 [INF] Request finished in 321.5334ms 500 text/html; charset=utf-8 (791a596a)
2019-04-19T09:31:19.1413420-04:00 0HLM4GQH12KMG:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:54470/api/Copyrights   (ca22a1cb)
2019-04-19T09:31:19.1524310-04:00 0HLM4GQH12KMG:00000003 [INF] Executing action method "MM.DataServices.Controllers.CopyrightsController.Get (MM.DataServices)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2019-04-19T09:31:19.1524870-04:00 0HLM4GQH12KMG:00000003 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2019-04-19T09:31:19.1525630-04:00 0HLM4GQH12KMG:00000003 [INF] Executed action "MM.DataServices.Controllers.CopyrightsController.Get (MM.DataServices)" in 0.1679ms (afa2e885)
2019-04-19T09:31:19.1526250-04:00 0HLM4GQH12KMG:00000003 [INF] Request finished in 11.3172ms 200 text/plain; charset=utf-8 (791a596a)
2019-04-19T09:31:19.1653200-04:00 0HLM4GQH12KMG:00000004 [INF] Request starting HTTP/1.1 GET http://localhost:54470/favicon.ico   (ca22a1cb)
2019-04-19T09:31:19.4133660-04:00 0HLM4GQH12KMG:00000004 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.IO.FileNotFoundException: Could not find file '/MM/Projects/MM.DataServices/MM.DataServices/wwwroot/lg/index.html'.
File name: '/MM/Projects/MM.DataServices/MM.DataServices/wwwroot/lg/index.html'
   at System.IO.FileInfo.get_Length()
   at Microsoft.AspNetCore.Http.SendFileResponseExtensions.SendFileAsyncCore(Stream outputStream, String fileName, Int64 offset, Nullable`1 count, CancellationToken cancel)
   at MM.DataServices.Startup.<>c__DisplayClass5_0.<<Configure>b__1>d.MoveNext() in /MM/Projects/MM.DataServices/MM.DataServices/Startup.cs:line 145
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2019-04-19T09:31:19.4203050-04:00 0HLM4GQH12KMG:00000004 [INF] Request finished in 254.996ms 500 text/html; charset=utf-8 (791a596a)
2019-04-19T09:31:21.4157250-04:00 0HLM4GQH12KMG:00000005 [INF] Request starting HTTP/1.1 GET http://localhost:54470/api/Copyrights   (ca22a1cb)
2019-04-19T09:31:21.4159280-04:00 0HLM4GQH12KMG:00000005 [INF] Executing action method "MM.DataServices.Controllers.CopyrightsController.Get (MM.DataServices)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2019-04-19T09:31:21.4160010-04:00 0HLM4GQH12KMG:00000005 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2019-04-19T09:31:21.4161000-04:00 0HLM4GQH12KMG:00000005 [INF] Executed action "MM.DataServices.Controllers.CopyrightsController.Get (MM.DataServices)" in 0.1966ms (afa2e885)
2019-04-19T09:31:21.4162650-04:00 0HLM4GQH12KMG:00000005 [INF] Request finished in 0.5822ms 200 text/plain; charset=utf-8 (791a596a)
2019-04-19T09:31:21.4351740-04:00 0HLM4GQH12KMG:00000006 [INF] Request starting HTTP/1.1 GET http://localhost:54470/favicon.ico   (ca22a1cb)
2019-04-19T09:31:21.7067270-04:00 0HLM4GQH12KMG:00000006 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.IO.FileNotFoundException: Could not find file '/MM/Projects/MM.DataServices/MM.DataServices/wwwroot/lg/index.html'.
File name: '/MM/Projects/MM.DataServices/MM.DataServices/wwwroot/lg/index.html'
   at System.IO.FileInfo.get_Length()
   at Microsoft.AspNetCore.Http.SendFileResponseExtensions.SendFileAsyncCore(Stream outputStream, String fileName, Int64 offset, Nullable`1 count, CancellationToken cancel)
   at MM.DataServices.Startup.<>c__DisplayClass5_0.<<Configure>b__1>d.MoveNext() in /MM/Projects/MM.DataServices/MM.DataServices/Startup.cs:line 145
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2019-04-19T09:31:21.7101590-04:00 0HLM4GQH12KMG:00000006 [INF] Request finished in 274.9984ms 500 text/html; charset=utf-8 (791a596a)
2019-04-19T09:31:22.5859490-04:00 0HLM4GQH12KMG:00000007 [INF] Request starting HTTP/1.1 GET http://localhost:54470/api/Copyrights   (ca22a1cb)
2019-04-19T09:31:22.5861370-04:00 0HLM4GQH12KMG:00000007 [INF] Executing action method "MM.DataServices.Controllers.CopyrightsController.Get (MM.DataServices)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2019-04-19T09:31:22.5861990-04:00 0HLM4GQH12KMG:00000007 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2019-04-19T09:31:22.5862700-04:00 0HLM4GQH12KMG:00000007 [INF] Executed action "MM.DataServices.Controllers.CopyrightsController.Get (MM.DataServices)" in 0.1616ms (afa2e885)
2019-04-19T09:31:22.5863350-04:00 0HLM4GQH12KMG:00000007 [INF] Request finished in 0.4042ms 200 text/plain; charset=utf-8 (791a596a)
2019-04-19T09:31:22.6041390-04:00 0HLM4GQH12KMG:00000008 [INF] Request starting HTTP/1.1 GET http://localhost:54470/favicon.ico   (ca22a1cb)
2019-04-19T09:31:22.8416600-04:00 0HLM4GQH12KMG:00000008 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.IO.FileNotFoundException: Could not find file '/MM/Projects/MM.DataServices/MM.DataServices/wwwroot/lg/index.html'.
File name: '/MM/Projects/MM.DataServices/MM.DataServices/wwwroot/lg/index.html'
   at System.IO.FileInfo.get_Length()
   at Microsoft.AspNetCore.Http.SendFileResponseExtensions.SendFileAsyncCore(Stream outputStream, String fileName, Int64 offset, Nullable`1 count, CancellationToken cancel)
   at MM.DataServices.Startup.<>c__DisplayClass5_0.<<Configure>b__1>d.MoveNext() in /MM/Projects/MM.DataServices/MM.DataServices/Startup.cs:line 145
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2019-04-19T09:31:22.8453160-04:00 0HLM4GQH12KMG:00000008 [INF] Request finished in 241.2148ms 500 text/html; charset=utf-8 (791a596a)
2019-04-19T09:35:43.8398290-04:00 0HLM4GQH12KMF:00000002 [INF] Request starting HTTP/1.1 POST http://localhost:54470/services/common/getstates  0 (ca22a1cb)
2019-04-19T09:35:43.8527720-04:00 0HLM4GQH12KMF:00000002 [INF] Successfully validated the token. (60169667)
2019-04-19T09:35:44.1171600-04:00 0HLM4GQH12KMF:00000002 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.IO.FileNotFoundException: Could not find file '/MM/Projects/MM.DataServices/MM.DataServices/wwwroot/lg/index.html'.
File name: '/MM/Projects/MM.DataServices/MM.DataServices/wwwroot/lg/index.html'
   at System.IO.FileInfo.get_Length()
   at Microsoft.AspNetCore.Http.SendFileResponseExtensions.SendFileAsyncCore(Stream outputStream, String fileName, Int64 offset, Nullable`1 count, CancellationToken cancel)
   at MM.DataServices.Startup.<>c__DisplayClass5_0.<<Configure>b__1>d.MoveNext() in /MM/Projects/MM.DataServices/MM.DataServices/Startup.cs:line 145
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2019-04-19T09:35:44.1240040-04:00 0HLM4GQH12KMF:00000002 [INF] Request finished in 284.2454ms 500 text/html; charset=utf-8 (791a596a)
2019-04-19T09:36:33.0063100-04:00 0HLM4GQH12KMF:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:54470/services/common/getstates   (ca22a1cb)
2019-04-19T09:36:33.0065150-04:00 0HLM4GQH12KMF:00000003 [INF] Successfully validated the token. (60169667)
2019-04-19T09:36:33.0117150-04:00 0HLM4GQH12KMF:00000003 [INF] Executing action method "MM.DataServices.Controllers.CommonController.GetStates (MM.DataServices)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2019-04-19T09:36:34.2958250-04:00 0HLM4GQH12KMF:00000003 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2019-04-19T09:36:34.3357440-04:00 0HLM4GQH12KMF:00000003 [INF] Executed action "MM.DataServices.Controllers.CommonController.GetStates (MM.DataServices)" in 1324.6993ms (afa2e885)
2019-04-19T09:36:34.3358490-04:00 0HLM4GQH12KMF:00000003 [INF] Request finished in 1329.5316ms 200 application/json; charset=utf-8 (791a596a)
2019-04-19T09:43:16.1204640-04:00 0HLM4PJSGI1N2:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:54470/api/Copyrights   (ca22a1cb)
2019-04-19T09:43:16.7986690-04:00 0HLM4PJSGI1N2:00000001 [INF] Executing action method "MM.DataServices.Controllers.CopyrightsController.Get (MM.DataServices)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2019-04-19T09:43:16.8301670-04:00 0HLM4PJSGI1N2:00000001 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2019-04-19T09:43:16.9075110-04:00 0HLM4PJSGI1N2:00000001 [INF] Executed action "MM.DataServices.Controllers.CopyrightsController.Get (MM.DataServices)" in 148.9406ms (afa2e885)
2019-04-19T09:43:16.9174080-04:00 0HLM4PJSGI1N2:00000001 [INF] Request finished in 814.8843ms 200 text/plain; charset=utf-8 (791a596a)
2019-04-19T09:43:17.0785510-04:00 0HLM4PJSGI1N2:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:54470/favicon.ico   (ca22a1cb)
2019-04-19T09:43:17.5855440-04:00 0HLM4PJSGI1N2:00000002 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.IO.FileNotFoundException: Could not find file '/MM/Projects/MM.DataServices/MM.DataServices/wwwroot/lg/index.html'.
File name: '/MM/Projects/MM.DataServices/MM.DataServices/wwwroot/lg/index.html'
   at System.IO.FileInfo.get_Length()
   at Microsoft.AspNetCore.Http.SendFileResponseExtensions.SendFileAsyncCore(Stream outputStream, String fileName, Int64 offset, Nullable`1 count, CancellationToken cancel)
   at MM.DataServices.Startup.<>c__DisplayClass5_0.<<Configure>b__1>d.MoveNext() in /MM/Projects/MM.DataServices/MM.DataServices/Startup.cs:line 145
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2019-04-19T09:43:17.6942350-04:00 0HLM4PJSGI1N2:00000002 [INF] Request finished in 615.7003ms 500 text/html; charset=utf-8 (791a596a)
2019-04-19T09:43:38.6702420-04:00 0HLM4PJSGI1N5:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:54470/services/common/getstates   (ca22a1cb)
2019-04-19T09:43:38.9158630-04:00 0HLM4PJSGI1N5:00000001 [INF] Successfully validated the token. (60169667)
2019-04-19T09:43:38.9453450-04:00 0HLM4PJSGI1N5:00000001 [INF] Authorization was successful for user: "marc_manuel@hotmail.com". (d7eb274a)
2019-04-19T09:43:38.9461670-04:00 0HLM4PJSGI1N5:00000001 [INF] Executing action method "MM.DataServices.Controllers.CommonController.GetStates (MM.DataServices)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2019-04-19T09:43:42.2160650-04:00 0HLM4PJSGI1N5:00000001 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2019-04-19T09:43:42.2636540-04:00 0HLM4PJSGI1N5:00000001 [INF] Executed action "MM.DataServices.Controllers.CommonController.GetStates (MM.DataServices)" in 3340.1285ms (afa2e885)
2019-04-19T09:43:42.2637910-04:00 0HLM4PJSGI1N5:00000001 [INF] Request finished in 3593.4725ms 200 application/json; charset=utf-8 (791a596a)
2019-04-19T09:44:41.9470220-04:00 0HLM4PJSGI1N5:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:54470/services/common/getstates   (ca22a1cb)
2019-04-19T09:44:41.9501450-04:00 0HLM4PJSGI1N5:00000002 [INF] Authorization failed for user: null. (a4ab1676)
2019-04-19T09:44:41.9550480-04:00 0HLM4PJSGI1N5:00000002 [INF] Authorization failed for the request at filter '"Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter"'. (8b6446cb)
2019-04-19T09:44:41.9781580-04:00 0HLM4PJSGI1N5:00000002 [INF] Executing ChallengeResult with authentication schemes ([]). (f3dca807)
2019-04-19T09:44:42.0004460-04:00 0HLM4PJSGI1N5:00000002 [INF] AuthenticationScheme: "Bearer" was challenged. (d45f1f38)
2019-04-19T09:44:42.0004990-04:00 0HLM4PJSGI1N5:00000002 [INF] Executed action "MM.DataServices.Controllers.CommonController.GetStates (MM.DataServices)" in 51.0211ms (afa2e885)
2019-04-19T09:44:42.0026910-04:00 0HLM4PJSGI1N5:00000002 [INF] Request finished in 55.6923ms 401  (791a596a)
2019-04-19T09:45:33.2016640-04:00 0HLM4PJSGI1N5:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:54470/services/common/getrecentnews   (ca22a1cb)
2019-04-19T09:45:33.2039110-04:00 0HLM4PJSGI1N5:00000003 [INF] Executing action method "MM.DataServices.Controllers.CommonController.GetRecentNews (MM.DataServices)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2019-04-19T09:45:33.4457340-04:00 0HLM4PJSGI1N5:00000003 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2019-04-19T09:45:33.4596220-04:00 0HLM4PJSGI1N5:00000003 [INF] Executed action "MM.DataServices.Controllers.CommonController.GetRecentNews (MM.DataServices)" in 255.7661ms (afa2e885)
2019-04-19T09:45:33.4597790-04:00 0HLM4PJSGI1N5:00000003 [INF] Request finished in 258.1083ms 200 application/json; charset=utf-8 (791a596a)
2019-04-19T09:45:45.5349730-04:00 0HLM4PJSGI1N5:00000004 [INF] Request starting HTTP/1.1 GET http://localhost:54470/services/common/getstates   (ca22a1cb)
2019-04-19T09:45:45.5351590-04:00 0HLM4PJSGI1N5:00000004 [INF] Authorization failed for user: null. (a4ab1676)
2019-04-19T09:45:45.5352030-04:00 0HLM4PJSGI1N5:00000004 [INF] Authorization failed for the request at filter '"Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter"'. (8b6446cb)
2019-04-19T09:45:45.5353050-04:00 0HLM4PJSGI1N5:00000004 [INF] Executing ChallengeResult with authentication schemes ([]). (f3dca807)
2019-04-19T09:45:45.5353780-04:00 0HLM4PJSGI1N5:00000004 [INF] AuthenticationScheme: "Bearer" was challenged. (d45f1f38)
2019-04-19T09:45:45.5354000-04:00 0HLM4PJSGI1N5:00000004 [INF] Executed action "MM.DataServices.Controllers.CommonController.GetStates (MM.DataServices)" in 0.2814ms (afa2e885)
2019-04-19T09:45:45.5354710-04:00 0HLM4PJSGI1N5:00000004 [INF] Request finished in 0.5683ms 401  (791a596a)
2019-04-19T09:45:50.3019730-04:00 0HLM4PJSGI1N5:00000005 [INF] Request starting HTTP/1.1 GET http://localhost:54470/services/common/getstates   (ca22a1cb)
2019-04-19T09:45:50.3021670-04:00 0HLM4PJSGI1N5:00000005 [INF] Authorization failed for user: null. (a4ab1676)
2019-04-19T09:45:50.3022080-04:00 0HLM4PJSGI1N5:00000005 [INF] Authorization failed for the request at filter '"Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter"'. (8b6446cb)
2019-04-19T09:45:50.3022400-04:00 0HLM4PJSGI1N5:00000005 [INF] Executing ChallengeResult with authentication schemes ([]). (f3dca807)
2019-04-19T09:45:50.3022650-04:00 0HLM4PJSGI1N5:00000005 [INF] AuthenticationScheme: "Bearer" was challenged. (d45f1f38)
2019-04-19T09:45:50.3022840-04:00 0HLM4PJSGI1N5:00000005 [INF] Executed action "MM.DataServices.Controllers.CommonController.GetStates (MM.DataServices)" in 0.1507ms (afa2e885)
2019-04-19T09:45:50.3024660-04:00 0HLM4PJSGI1N5:00000005 [INF] Request finished in 0.5209ms 401  (791a596a)
2019-04-19T09:46:46.3253290-04:00 0HLM4PJSGI1N5:00000006 [INF] Request starting HTTP/1.1 GET http://localhost:54470/services/common/getstates   (ca22a1cb)
2019-04-19T09:46:46.3262110-04:00 0HLM4PJSGI1N5:00000006 [INF] Successfully validated the token. (60169667)
2019-04-19T09:46:46.3263890-04:00 0HLM4PJSGI1N5:00000006 [INF] Authorization was successful for user: "marc_manuel@hotmail.com". (d7eb274a)
2019-04-19T09:46:46.3264390-04:00 0HLM4PJSGI1N5:00000006 [INF] Executing action method "MM.DataServices.Controllers.CommonController.GetStates (MM.DataServices)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2019-04-19T09:46:46.4225480-04:00 0HLM4PJSGI1N5:00000006 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2019-04-19T09:46:46.4227670-04:00 0HLM4PJSGI1N5:00000006 [INF] Executed action "MM.DataServices.Controllers.CommonController.GetStates (MM.DataServices)" in 96.397ms (afa2e885)
2019-04-19T09:46:46.4228370-04:00 0HLM4PJSGI1N5:00000006 [INF] Request finished in 97.5353ms 200 application/json; charset=utf-8 (791a596a)
